apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-client-service"
spec:
  selector:
    app: client
  type: ClusterIP
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.containerPort }}
