apiVersion: apps/v1
kind : Deployment
metadata: 
  name: canary-server-deployment
spec:
  selector: 
    matchLabels:
      app: {{ .Values.server.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.server.labels.app }}
    spec:
      initContainers:
      - name: wait-for-mongo
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for MongoDB to be ready..."
          until nc -z mongo 27017; do
            echo "MongoDB not ready, waiting..."
            sleep 5
          done
          echo "MongoDB is ready!"
      containers:
      - name: server
        image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
        ports:
        - containerPort: {{ .Values.server.containerPort }}
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-server-config"
              key: NODE_ENV
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-server-secret"
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-server-secret"
              key: JWT_SECRET
        resources:
          requests:
            cpu: {{ .Values.server.resources.requests.cpu }}
            memory: {{ .Values.server.resources.requests.memory }}
          limits:
            cpu: {{ .Values.server.resources.limits.cpu }}
            memory: {{ .Values.server.resources.limits.memory }}
   #   imagePullSecrets:
    #  - name: ecr-cred
